style: pre commit reg exp

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,5 +1,5 @@
 if ! head -1 "$1" | grep -qE "^(breaking|chore|ci|docs|feat|fix|refactor|security|style|test)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo "Aborting commit. Your commit message is invalid. Use ^(breaking|chore|ci|docs|feat|fix|refactor|security|style|test)(\(.+?\))?: .{1,}$" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
